### ISSUE TITLE
Nations number on page "Create Custom Game" is shown random.

### ISSUE THREAD

**Issue by evorios** [EaW1805/www#13]
Usually - three, occasionally - 17.

**Comment by ichatz** [comment]
Page updated - nations that do not participate in a scenario (e.g. 1808) are automatically hidden.

**Comment by evorios** [comment]
With your permission, I want to correct you:

``` javascript
    function showAllNations() {
        for (i = 1; i <= 17; i++) {
            $("#nation_" + i).show();
        }
    }

    function hideNations1808() {
        for (i = 1; i < 4; i++) {
            $("#nation_" + i).hide();
        }
        for (i = 7; i <= 17; i++) {
            $("#nation_" + i).hide();
        }
    }
```

Regards!

**Comment by ichatz** [comment]
Thanks for the fix - I fixed it online and then forgot to make the update on the sources... with the new version deployed the fix was lost...
